name: LLVM Toolchain Build

on:
  workflow_dispatch:
    branches:
      - main

  schedule:
    - cron: '0 17 * * 5'

env:
  TZ: Asia/Jakarta
  llvm_url: https://github.com/llvm/llvm-project

jobs:
  cloning:
    name: Cloning Project (llvm source)
    runs-on: ubuntu-latest
    container:
      image: mhmmdfdlyas/dockerfile:t-ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ccache
        run: |
          apt update
          apt install -y ccache
          ccache --set-config max_size=20G
          ccache --set-config compression=true
          ccache --set-config compression_level=5
          ccache -z

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: llvm-ccache-${{ runner.os }}-${{ hashFiles('tc_scripts/build.sh') }}
          restore-keys: |
            llvm-ccache-${{ runner.os }}-

      - name: Clone LLVM source
        run: |
          git clone --single-branch "${llvm_url}" -b main src/llvm-project --depth=1
          sed -i 's/set(LLVM_VERSION_SUFFIX.*/set(LLVM_VERSION_SUFFIX "")/' \
            src/llvm-project/cmake/Modules/LLVMVersion.cmake

      - name: Cache llvm source
        uses: actions/cache/save@v4
        with:
          path: src/llvm-project
          key: llvm-src-${{ runner.os }}-${{ hashFiles('tc_scripts/**') }}
          restore-keys: |
            llvm-src-${{ runner.os }}-

  profile:
    name: Build LLVM (profile)
    needs: cloning
    runs-on: ubuntu-latest
    container:
      image: mhmmdfdlyas/dockerfile:t-ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ccache
        run: |
          apt update
          apt install -y ccache
          ccache --set-config max_size=20G
          ccache --set-config compression=true
          ccache --set-config compression_level=5
          ccache -z

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: llvm-ccache-${{ runner.os }}-${{ hashFiles('tc_scripts/build.sh') }}
          restore-keys: |
            llvm-ccache-${{ runner.os }}-

      - name: Restore llvm source cache
        uses: actions/cache/restore@v4
        with:
          path: src/llvm-project
          key: llvm-src-${{ runner.os }}-${{ hashFiles('tc_scripts/**') }}
          restore-keys: |
            llvm-src-${{ runner.os }}-

      - name: Build profile
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ghuser_name: ${{ secrets.GHUSER_NAME }}
          ghuser_email: ${{ secrets.GHUSER_EMAIL }}
        run: ./tc_scripts/init.sh profile

      - name: Cleanup build artifacts (keep profdata.prof only)
        run: find build/llvm/instrumented -type f ! -name 'profdata.prof' -delete

      - name: Cache profdata + llvm source
        uses: actions/cache/save@v4
        with:
          path: |
            build/llvm/instrumented
            src/llvm-project
          key: llvm-profdata-${{ runner.os }}--${{ hashFiles('tc_scripts/build.sh') }}
          restore-keys: |
            llvm-profdata-${{ runner.os }}-

  final:
    name: Build LLVM (final)
    needs: profile
    runs-on: ubuntu-latest
    container:
      image: mhmmdfdlyas/dockerfile:t-ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ccache
        run: |
          apt update
          apt install -y ccache
          ccache --set-config max_size=20G
          ccache --set-config compression=true
          ccache --set-config compression_level=5
          ccache -z

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: llvm-ccache-${{ runner.os }}-${{ hashFiles('tc_scripts/build.sh') }}
          restore-keys: |
            llvm-ccache-${{ runner.os }}-

      - name: Restore profdata + llvm source cache
        uses: actions/cache/restore@v4
        with:
          path: |
            build/llvm/instrumented
            src/llvm-project
          key: llvm-profdata-${{ runner.os }}--${{ hashFiles('tc_scripts/build.sh') }}
          restore-keys: |
            llvm-profdata-${{ runner.os }}-

      - name: Build final
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ghuser_name: ${{ secrets.GHUSER_NAME }}
          ghuser_email: ${{ secrets.GHUSER_EMAIL }}
        run: ./tc_scripts/init.sh final

      - name: Show ccache stats
        if: always()
        run: |
          ccache -s
